---
cluster_name: cluster

kubernetes:
  version: 1.2.4
  masterApiPort: 443
  masterApiUrl: "https://{{ hostvars[groups['kubernetes-master'][0]]['privateIP'] }}"
  masterSan: []
  serviceNetwork: 10.245.0.0/16
  binaryUrlPrefix: https://storage.googleapis.com/kubernetes-release/release
  imagePrefix: gcr.io/google_containers
  cloudProvider: ""

etcd:
  initialToken: "{{ cluster_name }}"
  hosts: "{{ groups['kubernetes-master'] | map('extract', hostvars, 'privateIP') | map('regex_replace', '(.*)', 'http://\\1:2379') | list }}"

paths:
  localSslDir: ssl_ca/
