- name: CA | {{ item }} | ensure csr exists
  template:
    src: "{{ item }}-csr.j2"
    dest: "{{ LOCAL_SSL_DIR }}/{{ item }}-csr.json"
  delegate_to: 127.0.0.1
  run_once: true
  register: pki_cert_csr

- name: CA | {{ item }} | check if cert exists
  stat:
    path: "{{ LOCAL_SSL_DIR }}/{{ item }}.pem"
  delegate_to: 127.0.0.1
  run_once: true
  register: pki_cert_pem

- name: CA | {{ item }} | generate certificates
  shell: "cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=server {{ item }}-csr.json | cfssljson -bare {{ item }}"
  args:
    chdir: "{{ LOCAL_SSL_DIR }}"
  delegate_to: 127.0.0.1
  run_once: true
  when: pki_cert_csr | changed or not pki_cert_pem.stat.exists

