---
- hosts: coreos
  gather_facts: false
  roles:
  - coreos-bootstrap

- hosts: kubernetes
  roles:
  - kubernetes-parameters
  - kubernetes-pki

- hosts: etcd
  become: yes
  become_user: root
  roles:
  - kubernetes-parameters
  - etcd-node

- hosts: kubernetes-master
  become: yes
  become_user: root
  roles:
  - kubernetes-parameters
  - kubernetes-master

- hosts: kubernetes-worker
  become: yes
  become_user: root
  roles:
  - kubernetes-parameters
  - kubernetes-worker

