---
- hosts: coreos
  gather_facts: false
  roles:
  - defunctzombie.coreos-bootstrap
  tasks:
  - name: install httplib2
    pip: name=httplib2

- hosts: etcd
  become: yes
  become_user: root
  roles:
  - etcd-node

- hosts: master
  become: yes
  become_user: root
  roles:
  - kubernetes-master

- hosts: minions
  become: yes
  become_user: root
  roles:
  - kubernetes-worker

