- set_fact:
    kubernetes: >
      {{ kubernetes | default({}) | combine(
        {
          'serviceIpApi': kubernetes['serviceNetwork'] | ipaddr('net') | ipaddr(1) | ipaddr('address'),
          'serviceIpDns': kubernetes['serviceNetwork'] | ipaddr('net') | ipaddr(10) | ipaddr('address'),
          'hyperkubeImage': kubernetes['imagePrefix'] + '/hyperkube-amd64:v' + kubernetes['version'],
          'binaryUrl': kubernetes['binaryUrlPrefix'] + '/v' + kubernetes['version'] + '/bin/linux/amd64'
        }
      )}}

- debug:
    msg: >
     etcd: {{ etcd | to_nice_yaml }}
     kubernetes: {{ kubernetes | to_nice_yaml }}
