- name: Starting kubelet service
  service: name=kubelet state=started

- name: Ensure kubelet will start after boot
  service: name=kubelet enabled=yes

- name: Waiting for API to start (stay patient - pulling images)
  wait_for: host=127.0.0.1 port=8080

- name: Creating Kubernetes namespace
  uri: >
    method=POST
    url=http://127.0.0.1:8080/api/v1/namespaces
    body='{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"kube-system"}}'
    body_format=json
  register: kube_result
  run_once: true
  failed_when: >
      not (kube_result.status == 201 or (
          kube_result.status == 409 and
          'already exists' in kube_result.json.message))
  changed_when: "kube_result.status == 201"

- name: create addons folder
  become: yes
  file:
    path: /etc/kubernetes/addons
    state: directory
    mode: "0755"

- include: addon.yaml name=dns enabled=true
  run_once: true

- include: addon.yaml name=dashboard enabled=true
  run_once: true
