---
- name: flocker-ca create-control-certificate
  shell: "/ansible/flocker/bin/flocker-ca create-control-certificate {{ inventory_hostname }}"
  args:
    chdir: "{{ flocker_local_tempdir }}"
    creates: "control-{{ inventory_hostname }}.crt"
  delegate_to: 127.0.0.1

- name: copy control key to the control node
  copy:
    src: "{{ flocker_local_tempdir }}/control-{{ inventory_hostname }}.key"
    dest: /etc/flocker/control-service.key
    mode: 0600
  sudo: yes

- name: copy control cert to the control node
  copy:
    src: "{{ flocker_local_tempdir }}/control-{{ inventory_hostname }}.crt"
    dest: /etc/flocker/control-service.crt
  notify:
    - restart flocker-control
  sudo: yes
