---

- name: create certificate directory
  file:
    path: "{{ flocker_local_tempdir }}"
    state: directory
  delegate_to: 127.0.0.1
  run_once: true

- name: flocker-ca initialize
  shell: "/ansible/flocker/bin/flocker-ca initialize {{ flocker_cluster_name }}"
  args:
    chdir: "{{ flocker_local_tempdir }}"
    creates: "cluster.crt"
  delegate_to: 127.0.0.1
  run_once: true

- name: flocker-ca create-api-certificate kubelet
  shell: "/ansible/flocker/bin/flocker-ca create-api-certificate kubelet"
  args:
    chdir: "{{ flocker_local_tempdir }}"
    creates: "kubelet.crt"
  delegate_to: 127.0.0.1
  run_once: true

- name: create /etc/flocker on the node
  file:
    path: /etc/flocker
    state: directory
    mode: 0700
  become: yes

- name: copy cluster.crt to the node
  copy:
    src: "{{ flocker_local_tempdir }}/cluster.crt"
    dest: /etc/flocker/cluster.crt
  become: yes

- include: configure_control_service.yml
  when: "'{{ flocker_control_service_groupname }}' in group_names"

- include: configure_agent.yml
  when: "'{{ flocker_agents_groupname }}' in group_names"
