- name: Create /opt/bin
  file: name=/opt/bin state=directory

- name: Download kubelet binary
  get_url: url={{ kubernetes.binaryUrl }}/kubelet dest=/opt/bin/kubelet-{{ kubernetes.version }} mode=0755

- name: Setting up symbolic link to binary;
  file: src=/opt/bin/kubelet-{{ kubernetes.version }} dest=/opt/bin/kubelet state=link

